### ISSUE TITLE
replace ext-oauth

### ISSUE THREAD

**Issue by TimOgilvy** [intuit/QuickBooks-V3-PHP-SDK#10]
It would be nice to see this SDK be less dependant on ageing PECL libararies, and more compliant with real-world modern PHP standards such as PSR-4

Recommend replacing ext-oauth with https://github.com/FriendsOfSymfony/oauth2-php as soon as reasonably possible.

Good SDK's don't force users to install extensions, they use composer libraries.

This is not either A) a good SDK   B) A well documented SDK.

It's basically just a dirty clone of the .net and java sdk's.  Intuit is treating PHP developers as second class citizens. Not OK.

**Comment by TimOgilvy** [comment]
Alternative might be to use guzzle https://github.com/guzzle/guzzle

**Comment by hlu2** [comment]
Hi Tim,

Thanks for your sincerely comment. I believe many other PHP developers also share the same feelings when they use our PHP SDK. It is not user friendly, and it is out-dated. We won't blame anybody, it is our fault.

The development of Quickbooks PHP SDK have been in chaos since the beginning. When I took it over from previous owners, I had the exact same feeling as what you feel now, only worse. I read through the code and the issues coming out from my head unstoppable. There was one time I simply want to point developers to use the other PHP SDK, consolibyte, so I don't need to worry about it any more. 

However, it does not solve the problems. Developers need a good PHP SDK for QuickBooks Online and there is not one available yet, not even the consolibyte one. I need to take the responsibility to make our SDK good so people can call QuickBooks Online API happily, and easily. The only thing I ask from you guys is to give some patient. Right now I am the only developer who is responsible to re-write our SDK, and re-write takes times. I will make new release one by one, each addressing a issue. The Removing PECL OAuth extension is on my list. 

If you have any good suggestions, feel free to E-mail me at Hao_Lu@intuit.com or just leave a comment here. 

Again, thanks for your sincerely Comments
Hao

**Comment by TimOgilvy** [comment]
Hao this is a lovely response, and I really appreciate your candour.  I do think that if intuit are promoting their product as having a PHP SDK then they need to start paying someone else to help you with this work.  I just convinced quite a large company to use Quickbooks on the basis of there being a PHP SDK, because all the documentation suggested it would work.

If I come up with anything useful I will be sure to submit a pull request, but I don't think it's fair for intuit to be using the developer community to increase their profit.

**Comment by nikolov-tmw** [comment]
Just to join in on this discussion - is there any way to at least remove the [extension check](https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/master/src/Core/HttpClients/SyncRestHandler.php#L207)? We can't install the OAuth extension on our server at the moment, so decided to opt for a drop-in replacement( https://github.com/vclayton/unpecl-oauth ). However that check was preventing us from using the SDK.

Things seem to be working properly with the replacement so far after commenting out that check. People will get an exception one way or the other if they don't have the proper extension or the OAuth classes in place, but at least we can use an alternative that does not require installing an extension.

**Comment by becquerel** [comment]
@nikolov-tmw if I remember correctly, you might be able to get around this issue temporarily by calling composer with `--ignore-platform-reqs` option:
https://getcomposer.org/doc/03-cli.md#install

"--ignore-platform-reqs: ignore php, hhvm, lib-* and ext-* requirements and force the installation even if the local machine does not fulfill these. See also the platform config option."

**Comment by nikolov-tmw** [comment]
@becquerel oh - I didn't know about that. However there is also a check inside of the file I linked to above( https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/master/src/Core/HttpClients/SyncRestHandler.php#L207 ) - so that even if you manage to install the SDK(we use composer locally and then upload the files to the server, so that is not so much of a problem), you still can't use it unless you edit the `SyncRestHandler`.

**Comment by TimOgilvy** [comment]
I'm not sure whether the fail-on-absent scenario with composer is a broken part of the way that this repo works, or an issue with the way composer works - certainly the `--ignore-platform-reqs` makes that more like a feature and less like an issue.

Any kind of abstraction that makes PECL Oauth an option rather than a requirement would be good - ideally an interface allowing a custom Oauth module to be coded in by any developer against the interface.

**Comment by hlu2** [comment]
OAuth PECL OAuth extension has been removed.

Thanks
hao

**Comment by TimOgilvy** [comment]
thanks @hlu2, good to see. Has taken me some time to come back to this, but will test it again!
