### ISSUE TITLE
Requests / responses are always logged

### ISSUE THREAD

**Issue by ljudbane** [intuit/QuickBooks-V3-PHP-SDK#104]
Hello.

I'm using version v4.0.1 and i've noticed that all requests and responses get logged to /tmp even when i call DataService->disableLog(). After debugging i've located the issue in LogRequestsToDisk, line 60.
There is a check `if ($this->EnableServiceRequestsLogging) {` but this is always true because that value is "FALSE", a string with value "FALSE".

If logging flag value will be string "TRUE" and "FALSE" then additional checks have to be made.

Is my reasoning correct or am i doing something wrong?

**Comment by hlu2** [comment]
@ljudbane Let me take a look

**Comment by tomilsinszki** [comment]
@hlu2 I'm also using v4.0.1 and I'm also experiencing the same issue. 

Calling `$dataService->disableLog();` has no effect.

**Comment by donwilson** [comment]
We ran out of inodes in our /tmp partition because of this SDK, please fix

**Comment by Jarrid** [comment]
This is definitely an issue - ran into it in dev and production.

**Comment by hlu2** [comment]
@all
I am changing the code and will check in tomorrow, a new release will made around 5:00 PM PST.

Thanks all for the wait.

hao

**Comment by brumiser1550** [comment]
@hlu2 Thanks for the update. I realized I created a dup issue and went ahead and closed that one.

**Comment by hlu2** [comment]
@all
Released. Please upgrade the SDK and let me if the fix works

**Comment by Jarrid** [comment]
HI - 
I can confirm that after the update, no more .txt files are logged to the /tmp directory.

Side Note:
Initially, after performing the update, I noticed that it was still logging items.  This was due to the fact that after setting up the dataService (and disabling logging), I was calling dataService->updateOAuth2Token, which apparently sets the defaults back in place (logging on, and default location of /tmp).  I added another dataService->disableLogging() after the updateOAuth2Token call, and verified the logging stopped.



On June 19, 2018 at 8:29:18 PM, Hao Lu (notifications@github.com) wrote:

Closed #104.
