### ISSUE TITLE
Event manager

### ISSUE THREAD

**Issue by SmetDenis** [intuit/QuickBooks-V3-PHP-SDK#156]
Hi,

Do you have some event manager?
I have to log any external requests and any errors (exceptions) with QB Online for my project.
So I would like to subscribe on any success/problem requests.

I'm sorry, I didn't find it in your docs.

Thanks and best regards.

**Comment by SmetDenis** [comment]
Really? =)
It's just logs, not events. I need something like trigger(), emit(), on() etc...
Continuously parse the logs is awful and bad practice. Especially if I have many instances and requests.

Really in such a serious product there are no such regular things?
I am disappointed...

**Comment by challgren** [comment]
That would be my guess just logs (I'm not an Intuit employee, just a developer like you). I don't think SDK version was well thought out when it started and @hlu2 has been given a very daunting task of picking up the pieces. As I've been doing, I see things wrong/broken and make a PR to get it fixed and help other developers out. I'd say since these features sound extremely important to you. You could modify the SDK to fit you needs and if you feel its something you'd want to contribute towards the SDK to allow other developers to use then create a PR.

**Comment by SmetDenis** [comment]
@challgren yeah, I understand that you are not QB SDK developer.
Thanks for your reply.

**Comment by hlu2** [comment]
@SmetDenis 
This will be a feature in the V4 SDK, but not in the current V3 PHP SDK. You will be able to add all different functionalities through $client.addInterceptors(...); function in the V4 SDK. You can use predefined Interceptors like Retry, logOnError, AutoRefreshToken, etc, or you can define your own logic, as long as it implements the Interceptor interface.

Adding in V3 is not a feasible solution as the PHP SDK did not provide an easy way to change it. It mainly used $ServiceContext so I cannot apply Dependency Injection here. That's why I put it on the V4 SDK.  

The prototype of V4 PHP SDK should be available around the end of this year. Send me your request to : Hao_Lu@intuit.com and I will put you on the early access list.

Thanks
Hao

@challgren  thanks for answering here!
