### ISSUE TITLE
Why EntityType is not coming while querying purchase data

### ISSUE THREAD

**Issue by onlinecheckwriter** [intuit/QuickBooks-V3-PHP-SDK#165]
Simple Problem:

1. - We want to get **EntityRef name**
2. -  We are getting  [EntityRef] while calling the api 
3. - But We are not getting Entity Type so we are not sure this EntityRef is customer,employee or vendor
4.  So we couldnt get EntityRef Name
5. If you use api explorer to test Purchase read function entityref and entitytype is coming

Our Code: 
--------------
```
 $purchase = $dataService->query("SELECT * FROM Purchase Where Id ='$txnId'");
print_r($purchase ) 
```

Result as following

```

(
--
  | [AccountRef] => 134
  | [PaymentMethodRef] =>
  | [PaymentRefNum] =>
  | [PaymentType] => Check
  | [CheckPayment] =>
  | [CreditCardPayment] =>
  | [EntityRef] => 68
  | [Credit] =>
  | [RemitToAddr] => QuickBooksOnline\API\Data\IPPPhysicalAddress Object
  | (
  | [Id] => 103
  | [Line1] => address1
  | [Line2] =>
  | [Line3] =>
  | [Line4] =>
  | [Line5] =>
  | [City] => AA
  | [Country] => United States
  | [CountryCode] =>
  | [CountrySubDivisionCode] => TX
  | [PostalCode] => 79444
  | [PostalCodeSuffix] =>
  | [Lat] =>
  | [Long] =>
  | [Tag] =>
  | [Note] =>
  | )
  |  
  | [TotalAmt] => 100.00
  | [Memo] =>
  | [PrintStatus] => NeedToPrint
  | [GlobalTaxCalculation] =>
  | [PurchaseEx] => QuickBooksOnline\API\Data\IPPIntuitAnyType Object
  | (
  | )
  |  
  | [DocNumber] =>
  | [TxnDate] => 2018-07-31
  | [DepartmentRef] =>
  | [CurrencyRef] => USD
  | [ExchangeRate] =>
  | [PrivateNote] => 100-VENDOR
  | [TxnStatus] =>
  | [LinkedTxn] =>
  | [Line] => QuickBooksOnline\API\Data\IPPLine Object
  | (
```

**Comment by pixelskribe** [comment]
This is due to the issue I raised about the XML parser being used in the SDK. It does not recognize or preserve any XML tag attributes. https://github.com/intuit/QuickBooks-V3-PHP-SDK/issues/163

For example the XML from the element you need looks like the following. 
``<EntityRef name="Squeaky Kleen Car Wash" type="Vendor">57</EntityRef>``
Here both the "name" and "type" attributes are lost, only the actual element value between the tags "57" is retained.

My project was time critical so I forked the sdk and replaced the parser with another, as explained in another thread.

**Comment by onlinecheckwriter** [comment]
Thank you.
