### ISSUE TITLE
No way to disable logging

### ISSUE THREAD

**Issue by tupto** [intuit/QuickBooks-V3-PHP-SDK#17]
Using the function ServiceContext->disableLog() does nothing as the LoggerBase class takes none of your settings into account. It always uses the CoreConstants::DEFAULT_LOGGINGLOCATION (which is also wrong as it tries to write to /tmp/IdLogsexecutionlog.txt and not /tmp/IdLogs/executionlog.txt like the documentation says). The LoggerBase classs also has no check to see if the user has disabled it before attempting to write to the file.

**Comment by hlu2** [comment]
Hi Tupto,

       There are two kinds of logs that we record. One is the "executationLog", which will have information like this:
Called GetBaseURL method.
GetSerializer
GetSerializer(Response): XML
GetSerializer
GetSerializer(Request): Xml
GetSerializer
GetSerializer(Request): Xml
GetSerializer
GetSerializer(Response): XML
Called Method Query.
GetSerializer
GetSerializer(Request): Xml
....

 and the other one is called "Request/Response Log", which will have information like this:
REQUEST URI FOR SEQUENCE ID 00003
==================================
https://qbonline-e2e.api.intuit.com/v3/company/193514489870599/query?minorversion=4

REQUEST HEADERS
================
host: qbonline-e2e.api.intuit.com
user-agent: V3PHPSDK3.0.0
accept: */*
connection: close
content-type: application/text
content-length: 52

REQUEST BODY
=============
select * from Account startPosition 1 maxResults 500

When you call $dataService->disableLog();
It will only disable the Request/Response Log(some users do not want to record the request and response for security reasons); however, for the execution log, right now it is always recorded. 

I didn't make it clear on the readme file, I will change it later today. However, for the pull request you submit, unfortunately, I can't accept it as it does not solve the issue. I will address it later.

Thanks for pointing it out :)

Hao

**Comment by cgunnels** [comment]
This is still an issue for me. All the requests response logs are getting put into the /tmp dir and eating up server space. i'm calling $dataService->disableLog()
`$dataService = DataService::Configure(array(
            'auth_mode' => 'oauth2',
            'ClientID' => xxxxxxxxx,
            'ClientSecret' => xxxxxxxxx,
            'accessTokenKey' => xxxxxxxxx,
            'refreshTokenKey' => xxxxxxxxx,
            'QBORealmID' => xxxxxxxxx,
            'baseUrl' => xxxxxxxxx
        ));
        $dataService->disableLog();`

**Comment by DIntriglia** [comment]
I can confirm that it is not working on my side as well. I just setup a cron jobs to remove every non sess file from the directory, which includes the Request & Response files from QBO. Extremely frustrating that you can't simply disable it, but at least there is a work around through a cron job.

`find /tmp/systemd-private-XXXXX-php74rc-fpm.service-XXXXXX/tmp/ -type f ! -name 'sess*' -delete`

Simply update for the correct systemd folder in your /tmp/ directory. Hope this helps!

**Comment by matttydubs** [comment]
Same issue here, any solutions?

**Comment by irozkov** [comment]
Hey,

If you run reports, you must also disable the log for service context. However, there is a bug in ServiceContext\disableLog(), which calls LocalConfigReader::setupLogger using the string "FALSE" instead of bool false to set LogRequestsToDisk::EnableServiceRequestsLogging. That causes LogPlatformRequests() to always treat LogRequestsToDisk::EnableServiceRequestsLogging as a truthy value. So, below works for me:

patch ServiceContext\disableLog: 

LocalConfigReader::setupLogger($_ippConfigInstance, CoreConstants::DEFAULT_LOGGINGLOCATION, "FALSE"); ->
LocalConfigReader::setupLogger($_ippConfigInstance, CoreConstants::DEFAULT_LOGGINGLOCATION, false);

Then:

$dataService = DataService::Configure([...]);
$dataService->disableLog();
$serviceContext = $getServiceContext();
$serviceContext->disableLog();

no more logs in /tmp

**Comment by gmariani** [comment]
Why was this closed and not actually patched in the SDK?
