### ISSUE TITLE
Adding CustomField to sales Receipt 

### ISSUE THREAD

**Issue by thedangler** [intuit/QuickBooks-V3-PHP-SDK#258]
Hello, I don't know if this is a bug or just my lack of understanding.
I'm trying to set a custom field for my sales receipt.  I have it working in python so I know its possible to set the custom fields I setup for sales receipts.
$s = SalesReceipt::create([
....
"CustomField" =>[["DefinitionId"=>"1", "Name"=>"Account Name", "StringValue" => "test"]]
]);
I do not get any errors but its not added to the sales receipt.

I've also tried after creating the sales receipt with basic info adding it after

$s = SalesReceipt::create([...]);
$s->CustomField = [new IPPCustomField(["DefinitionId"=>"1",'Name'=>"Account Name","StringValue"=>"testing"])];

No errors sales receipt is added but with no custom field data.

Anyone see what I'm doing wrong?

**Comment by fjolin-intuit** [comment]
Depends on what you named your Custom Field.  Do a read on Preferences and look at SalesFormsPrefs.CustomField Array.  It's possible that you have the Name and StringValue mixed up as they can be a tad confusing.  

For example my preferences return a custom field I have set up like so:
"CustomField": [
    {...},
    {
     "CustomField": [
      {
       "Name": "SalesFormsPrefs.SalesCustomName**1**",
       "Type": "StringType",
       "StringValue": "**Crew #**"
      }
     ]
    }
   ],

Then in the SalesReceipt the DefinitionID is the **1** inside prefs.CustomField.Name.  The SalesReceipt.CustomField.Name is the same as SalesFormsPrefs.Customfield.**StringValue**
      
Resulting SalesReceipt looks like so: 
`
"CustomField" => [[
        "DefinitionId" => "1",
        "StringValue" => "Member 2",
        "Type" => "StringType",
        "Name" => "Crew #"
      ]]
`

Our tutorials maps it out pretty well so that you can see the model. https://developer.intuit.com/app/developer/qbo/docs/develop/tutorials/create-custom-fields

**Comment by thedangler** [comment]
I dump my customer fields and the Definition ID is Null

`          +CustomField: array:2 [▼
            0 => IPPCustomField {#758 ▼
              +DefinitionId: null
              +Name: "SalesFormsPrefs.SalesCustomName2"
              +Type: "StringType"
              +StringValue: "Member Name"
              +BooleanValue: null
              +DateValue: null
              +NumberValue: null
            }
            1 => IPPCustomField {#769 ▼
              +DefinitionId: null
              +Name: "SalesFormsPrefs.SalesCustomName1"
              +Type: "StringType"
              +StringValue: "Account Name"
              +BooleanValue: null
              +DateValue: null
              +NumberValue: null
            }`

**Comment by moses-bowman** [comment]
I'm having a similar issue with @thedangler. The invoices don't get synced because every `DefinitionId` queried from `SalesFormsPrefs` are `null`. According to the [docs](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/most-commonly-used/invoice), a `CustomField`'s `DefinitionId` is **required**

![image](https://user-images.githubusercontent.com/40249465/113647674-dadf8880-96bd-11eb-8b99-588d4d78d75a.png)

![image](https://user-images.githubusercontent.com/40249465/113647391-5b51b980-96bd-11eb-9fb1-4d4f3f5ffc5a.png)
