### ISSUE TITLE
SSL certificate has expired

### ISSUE THREAD

**Issue by evancrose** [intuit/QuickBooks-V3-PHP-SDK#260]
Error in checking cURL version for TLS 1.2. Error Num:[60] Error message:[SSL certificate problem: certificate has expired]
thrown in /home/qbonline/vendor/quickbooks/v3-php-sdk/src/Core/HttpClients/BaseCurl.php on line 115

**Comment by evancrose** [comment]
The issue is that https://www.howsmyssl.com/a/check is having issues, which seems to break the entire SDK.

**Comment by leimd** [comment]
We can confirm that we are experiencing this issue as well

**Comment by tommystitch** [comment]
Can confirm that we are experiencing the same issue :(

**Comment by j-carlson** [comment]
Working around this issue for the time being by adding the following to the beginning of function versionOfTLS() in Core/HttpClients/BaseCurl.php:

`return 'TLS 1.3';`

Not great, but gets our production environment back up and running for now. Hoping howsmyssl comes back up soon.

**Comment by onlinecheckwriter** [comment]
We are experiencing same problem

[SSL certificate problem: certificate has expired] at /home/forge/app.onlinecheckwriter.com/vendor/quickbooks/v3-php-sdk-ocw/src/Core/HttpClients/BaseCurl.php:115

**Comment by wpaliwoda** [comment]
We are experiencing the same issue
```
PHP Fatal error: Uncaught QuickBooksOnline\\API\\Exception\\SdkException: [0]: Error in checking cURL version for TLS 1.2. Error Num:[60] Error message:[SSL certificate problem: certificate has expired]\n\n thrown in /var/www/prod/vendor/quickbooks/v3-php-sdk/src/Core/HttpClients/BaseCurl.php on line 115
```

**Comment by alejandro-carstens** [comment]
https://www.howsmyssl.com has an expired certificate.

**Comment by wpaliwoda** [comment]
I submitted an issue to the howsmyssl repo.  You can track it here:
https://github.com/jmhodges/howsmyssl/issues/275

**Comment by hlu2** [comment]
I will temporarily remove the check and make a new release for it.

**Comment by rafaelmaza** [comment]
@hlu2 might wanna merge this one? https://github.com/intuit/QuickBooks-V3-PHP-SDK/pull/262

**Comment by hlu2** [comment]
@rafaelmaza didn't see your pull request, however, we are doing the same thing. Let me know if you still see this error anymore.

**Comment by hlu2** [comment]
Fixed and released.

**Comment by rafaelmaza** [comment]
@hlu2 I've previously tested my changes and seems to work, so `v5.3.2` should be good

**Comment by rafaelmaza** [comment]
Looks like https://www.howsmyssl.com/a/check is back - however, it might be better not to rely on it going forward? A few extra thoughts around that:

- Is the intention of `BaseCurl::versionOfTLS` solely to ensure connections can be made using TLSv1.2+ (i.e. client supports it)?
- Assuming yes, could that be enforced in the actual requests instead of issuing a "pre-flight" check? Looks like this commented line would achieve that: https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/master/src/Core/HttpClients/CurlHttpClient.php#L152
- If the extra TLS verification request is needed for some reason, might be worthy to use a domain controlled by Intuit and force TLSv1.2 in cURL - which would make the connection fail if not supported, thus indicating if it is or isn't supported?

**Comment by hlu2** [comment]
@rafaelmaza The check is no longer needed. If you now call the service with tls 1.1 or below, a message : "OpenSSL was built without SSLv2 support" will be returned. When we just start deprecating tls 1.1, some PHP developers are not sure which tls version they are using, this check is a "helper" method for them. It should be removed after we officially deprecate tls 1.1 or below.
