### ISSUE TITLE
IPPLine has no external reference field

### ISSUE THREAD

**Issue by velocityfm** [intuit/QuickBooks-V3-PHP-SDK#29]
**PROBLEM:** There's currently no way to set an external reference (i.e. corresponding line item number in a different application) in the IPPLine class.

**DESCRIPTION:** The framework doesn't allow matching line items to external "equivalent" line items (i.e. the same line items in a different system than QuickBooks itself).  I would say this could be done by reloading the invoice after creating it then cycling through the line items and saving their respective reference back to our system, but there's no way to identify which line item is which unless you compare "like" attributes, which is dicey at best.

**PROPOSED SOLUTION:**  Add an external reference field ("ExternalRef" maybe), or a "MISC" field to hold meta-data.  This is what CustomField is for, but it's not usable in QBO.

**Comment by hlu2** [comment]
@velocityfm 
Thanks for sharing your use case. I have recorded your requirements and put it here: https://intuitdevelopergroup.uservoice.com/forums/182764-intuit-developer-group/suggestions/19607023-ippline-has-no-external-reference-field

As far as I know, QBO team are working on some features of IPPLine and there will be some updates around December this year(not sure if it will be related to your use case). The "CustomField" once existed for IPPLine in QuickBooks Desktop, but when they move it to QuickBooks Online, they removed it for various reasons. I think this is a valid request and I will talk to the QBO Team directly.

Since this is a QBO feature request instead of SDK, I will close it for now.
