### ISSUE TITLE
DataService allow access to ServiceContext

### ISSUE THREAD

**Issue by challgren** [intuit/QuickBooks-V3-PHP-SDK#6]
Developers should be able to access the ServiceContext in the DataService.

**Comment by hlu2** [comment]
v3.0.2, add:
$serviceContext = $dataService->getServiceContext();
for retrieving serviceContext.
However, since we have:

$dataService->setLogLocation("/Users/hlu2/Desktop/newFolderForLog");
$dataService->setMinorVersion("4");
$dataService->useXml();
$dataService->disableLog();

Getting the serviceContext is not necessary.

**Comment by challgren** [comment]
I wanted the data service so I can manually process a IPPFault response.

**Comment by challgren** [comment]
My solution was to write a wrapper and a new ObjectSerializer
