### ISSUE TITLE
PHP 7?

### ISSUE THREAD

**Issue by josephzidell** [intuit/QuickBooks-V3-PHP-SDK#9]
This package requires [OAuth](http://pecl.php.net/package/oauth) v1.2.3, which is only available up to [php 5.6](http://pecl.php.net/package/oauth/1.2.3/windows). Does this work with php 7.x?

**Comment by TimOgilvy** [comment]
I'm currently using the oauth extension with PHP 7 and it seems to be working okay for now.  It took me a long time to realise that the reason I couldn't install it on my AWS EBS AMI was because it was already installed tho!

It's a giant PIA to manage the extension against composer in the CLI and your server - composer install now fails on my mac, so I do all my composer work in a VM.  It's a bit of a PIA that this SDK explicitly requires ext-oauth in the CLI.  

It would have been nice to see this SDK built with something like 
https://github.com/FriendsOfSymfony/oauth2-php and
https://github.com/symfony/http-foundation

Rather than the ageing pecl oauth extension!

**Comment by josephzidell** [comment]
@hlu2 Are you open to swapping to one of the above-mentioned easier-to-install packages?

**Comment by hlu2** [comment]
Hi Joseph,

I need to make the JSON support out first, the removing PECL extension is on the release after tomorrow's release.

Thanks
hao

**Comment by TimOgilvy** [comment]
Hao just for your reference, you may notice that the API does not support JSON for all requests, and errors are frequently returned in HTML/XML rather than JSON.  I've added a request for this to be fixed to the intuit developer forum, but hopefully you can put some pressure on from the inside too.  

Good luck! I'm sure you must be very busy!

**Comment by josephzidell** [comment]
Thanks @hlu2

**Comment by hlu2** [comment]
@all
This is on progress now. Check the wiki page

**Comment by hlu2** [comment]
Completed.
